/**
 * Seeds Strapi from the approved design prototype.
 *
 * Content comes from scripts/design-content.json (generated by extract-design-content.mjs straight
 * out of the prototype) and from design/SEO-Content-Map.md. Nothing here is authored — the design
 * is approved and this is transcription.
 *
 * Idempotent: everything upserts by slug (or is a single type), so re-running is safe.
 *
 *   npm run seed
 */
import { createStrapi, compileStrapi } from '@strapi/strapi';
import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import sharp from 'sharp';

type Item = Record<string, any>;
const content = JSON.parse(readFileSync(resolve(__dirname, 'design-content.json'), 'utf8'));

const CACHE = resolve(__dirname, '.cache');

// ---------------------------------------------------------------------------------------------
// SEO — verbatim from design/SEO-Content-Map.md.
// The map specifies literal titles/descriptions for the fixed pages, and a *pattern* for the
// service/industry detail pages (the prototype's own seoFor() builds those the same way).
// ---------------------------------------------------------------------------------------------
const SEO = {
  home: {
    metaTitle: 'Forbes Water | Independent Water Treatment & Consulting Australia',
    metaDescription:
      'Independent water consulting, treatment, monitoring and management across Australia. Optimise water quality, cut costs and stay compliant. Request a consultation.',
  },
  about: {
    metaTitle: 'About Us | Forbes Water',
    metaDescription:
      "Meet Forbes Water — independent Australian water specialists with 18+ years' experience across 340+ sites. Chemists, engineers and scientists who start with the water, not a product catalogue.",
  },
  services: {
    metaTitle: 'Water Treatment & Consulting Services | Forbes Water',
    metaDescription:
      'Eight specialist water services — treatment, drinking water quality, wastewater, recycling, groundwater monitoring, testing, optimisation and strategy — from one independent Australian team.',
  },
  industries: {
    metaTitle: 'Industries We Serve | Forbes Water',
    metaDescription:
      "Sector-specific water expertise for mining, agriculture, commercial and industrial sites, government and hospitality — from Australia's independent water specialists.",
  },
  sustainability: {
    metaTitle: 'Sustainable Water Management | Forbes Water',
    metaDescription:
      'Water stewardship with measurable payback — demand reduction, recycling, environmental protection and credible ESG reporting from independent specialists.',
  },
  projects: {
    metaTitle: 'Projects & Case Studies | Forbes Water',
    metaDescription:
      'Water treatment, recycling and compliance case studies across mining, government, industry, agriculture and hospitality — with measured results.',
  },
  contact: {
    metaTitle: 'Contact Forbes Water | Request a Consultation',
    metaDescription:
      'Talk to a senior water specialist — not a sales rep. Consulting, treatment, monitoring and management Australia-wide. Response within one business day.',
  },
} as const;

/** Cap a description at a sentence boundary so generated meta stays under the field limit. */
function clamp(text: string, max = 180): string {
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  const stop = Math.max(cut.lastIndexOf('. '), cut.lastIndexOf('— '), cut.lastIndexOf(', '));
  return (stop > 80 ? cut.slice(0, stop) : cut).trim().replace(/[,—]$/, '') + '…';
}

async function main() {
  const app = await createStrapi(await compileStrapi()).load();
  app.log.level = 'error';

  const doc = (uid: string) => app.documents(uid as any);

  // Safety: seeding overwrites content by design (upsert). Once the site has content, a re-run would
  // clobber whatever the client edited in the admin. So we refuse to touch a populated database unless
  // explicitly forced. An empty database seeds normally.
  //   npm run seed              → fill an empty DB; skip (do nothing) if content already exists
  //   npm run seed -- --force   → reset ALL content to the design defaults (destructive)
  const FORCE = process.argv.includes('--force');
  if (!FORCE && (await doc('api::service.service').count({})) > 0) {
    console.log(
      'Content already present — skipping seed so admin edits are not overwritten.\n' +
        'To reset everything to the design defaults, run:  npm run seed -- --force'
    );
    await app.destroy();
    process.exit(0);
  }

  // -------------------------------------------------------------------------------------------
  // Media — the prototype points at Unsplash placeholders. We pull them into Strapi's Media
  // Library so the client can swap them for real photography without touching code.
  // Best-effort: seeding still succeeds offline, just without images.
  // -------------------------------------------------------------------------------------------
  const uploadCache = new Map<string, any>();
  const downloadCache = new Map<string, string>();
  let mediaFailures = 0;

  /**
   * Downloads are cached by URL (the design reuses a few Unsplash photos across slots), but each
   * content slot gets its OWN Media Library file, keyed by name.
   *
   * Deduplicating the uploads too would be tempting — fewer files — but it couples unrelated pages:
   * the client swaps one placeholder for real photography and silently changes a second page they
   * weren't editing. Independent files cost a little storage and avoid that trap.
   */
  async function uploadFromUrl(url: string, name: string): Promise<any | null> {
    if (uploadCache.has(name)) return uploadCache.get(name);
    try {
      if (!existsSync(CACHE)) mkdirSync(CACHE, { recursive: true });
      const file = resolve(CACHE, `${name}.jpg`);
      if (!existsSync(file)) {
        const cached = downloadCache.get(url);
        if (cached && existsSync(cached)) {
          writeFileSync(file, readFileSync(cached));
        } else {
          const res = await fetch(url);
          if (!res.ok) throw new Error(`HTTP ${res.status}`);
          writeFileSync(file, Buffer.from(await res.arrayBuffer()));
        }
      }
      downloadCache.set(url, file);
      const existing = await app.db.query('plugin::upload.file').findOne({ where: { name: `${name}.jpg` } });
      if (existing) {
        uploadCache.set(name, existing);
        return existing;
      }
      // NB: formidable's key is `originalFilename` (not `originalFileName`). Get it wrong and every
      // upload silently lands as "unamed", which also defeats the dedup lookup above.
      const [uploaded] = await app.plugin('upload').service('upload').upload({
        data: {},
        files: {
          filepath: file,
          originalFilename: `${name}.jpg`,
          mimetype: 'image/jpeg',
          size: readFileSync(file).length,
        },
      });
      uploadCache.set(name, uploaded);
      return uploaded;
    } catch (err: any) {
      mediaFailures++;
      app.log.warn(`media: ${name} → ${err.message}`);
      uploadCache.set(name, null);
      return null;
    }
  }

  /**
   * Uploads a bundled SVG illustration as a PNG (next/image rejects raw SVG unless
   * dangerouslyAllowSVG is on, which we don't want). Rasterised once, cached, then dropped into the
   * Media Library like any other asset — so it shows in the admin and the client can replace it.
   */
  async function uploadSvgAsPng(svgPath: string, name: string): Promise<any | null> {
    if (uploadCache.has(name)) return uploadCache.get(name);
    try {
      if (!existsSync(CACHE)) mkdirSync(CACHE, { recursive: true });
      const file = resolve(CACHE, `${name}.png`);
      if (!existsSync(file)) {
        const png = await sharp(readFileSync(svgPath)).png().toBuffer();
        writeFileSync(file, png);
      }
      const existing = await app.db.query('plugin::upload.file').findOne({ where: { name: `${name}.png` } });
      if (existing) {
        uploadCache.set(name, existing);
        return existing;
      }
      const [uploaded] = await app.plugin('upload').service('upload').upload({
        data: {},
        files: { filepath: file, originalFilename: `${name}.png`, mimetype: 'image/png', size: readFileSync(file).length },
      });
      uploadCache.set(name, uploaded);
      return uploaded;
    } catch (err: any) {
      mediaFailures++;
      app.log.warn(`media: ${name} → ${err.message}`);
      uploadCache.set(name, null);
      return null;
    }
  }

  const mediaFrame = async (url: string, name: string, label: string, alt: string) => ({
    image: await uploadFromUrl(url, name),
    label,
    alt,
  });

  // Three section photos are hardcoded in the prototype's markup (not its JS arrays): the home hero,
  // the home "Why" panel, and the About story. Transcribed verbatim from design/…dc.html.
  const U = (id: string, w = 1200) =>
    `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=60`;
  const SECTION_IMG = {
    homeHero: U('1559825481-12a05cc00344', 1400),
    homeWhy: U('1581092160562-40aa08e78837'),
    aboutStory: U('1521737604893-d14cc237f11d'),
  };

  /** Upsert by slug for collection types. */
  async function upsert(uid: string, slug: string, data: Item) {
    const existing = await doc(uid).findFirst({ filters: { slug: { $eq: slug } } as any });
    return existing
      ? doc(uid).update({ documentId: existing.documentId, data, status: 'published' } as any)
      : doc(uid).create({ data: { ...data, slug }, status: 'published' } as any);
  }

  /** Upsert a single type. */
  async function single(uid: string, data: Item, publish = true) {
    const existing = await doc(uid).findFirst();
    const status = publish ? 'published' : undefined;
    return existing
      ? doc(uid).update({ documentId: existing.documentId, data, status } as any)
      : doc(uid).create({ data, status } as any);
  }

  const num = (arr: Item[]) => arr.map((x) => ({ number: x.n, title: x.t, description: x.d }));
  const icon = (arr: Item[]) => arr.map((x) => ({ title: x.t, description: x.d }));
  const stat = (v: string, label: string) => ({ value: v, label });

  // -------------------------------------------------------------------------------------------
  // Industries first — services reference them.
  // -------------------------------------------------------------------------------------------
  const industryIds: Record<string, string> = {};
  for (const [i, ind] of content.industries.entries()) {
    const rec: any = await upsert('api::industry.industry', ind.slug, {
      title: ind.t,
      order: i,
      cardDescription: ind.d,
      h1: ind.h1,
      intro: ind.intro,
      media: await mediaFrame(ind.img, `industry-${ind.slug}`, ind.imgLabel, ind.imgLabel),
      challenges: icon(ind.challenges),
      stat: stat(ind.stat, ind.statD),
      seo: {
        metaTitle: `${ind.t} Water Solutions | Forbes Water`,
        metaDescription: clamp(ind.intro),
      },
    });
    industryIds[ind.slug] = rec.documentId;
  }

  // -------------------------------------------------------------------------------------------
  // Services — relatedIndustries is a ONE-WAY relation, ordered exactly as the design lists it.
  // -------------------------------------------------------------------------------------------
  const serviceIds: Record<string, string> = {};
  for (const [i, s] of content.services.entries()) {
    const rec: any = await upsert('api::service.service', s.slug, {
      title: s.t,
      order: i,
      short: s.short,
      blurb: s.blurb,
      h1: s.h1,
      tagline: s.tagline,
      overview: s.overview,
      media: await mediaFrame(s.img, `service-${s.slug}`, s.imgLabel, s.imgLabel),
      outcomes: icon(s.outcomes),
      steps: num(s.steps),
      // Optional client-added block; image is left empty so the built-in illustration shows until the
      // client uploads their own field photo in Strapi. Omit the key entirely when absent — passing
      // `featurePanel: undefined` makes Strapi's component updater throw ('id' in undefined).
      ...(s.featurePanel
        ? {
            featurePanel: {
              eyebrow: s.featurePanel.eyebrow,
              heading: s.featurePanel.heading,
              // The bundled illustration is uploaded to the Media Library so it shows in the admin and
              // the client can swap it for a real photo. No caption label — matches the design.
              media: {
                image: await uploadSvgAsPng(resolve(__dirname, 'assets/borehole-monitoring.svg'), `service-${s.slug}-feature`),
                alt: s.featurePanel.imgAlt,
              },
              points: s.featurePanel.points.map((text: string) => ({ text })),
            },
          }
        : {}),
      relatedIndustries: s.inds.map((x: Item) => industryIds[x.href.split('/').pop()!]).filter(Boolean),
      seo: {
        metaTitle: `${s.t} | Forbes Water`,
        metaDescription: clamp(
          `${s.t} for Australian industry and government. ${s.tagline} Independent advice from Forbes Water — request a consultation.`
        ),
      },
    });
    serviceIds[s.slug] = rec.documentId;
  }

  // Backfill industry.relatedServices — independent of service.relatedIndustries by design
  // (the prototype's cross-links are asymmetric; 10 edges do not mirror). Order is curated.
  for (const ind of content.industries) {
    await doc('api::industry.industry').update({
      documentId: industryIds[ind.slug],
      data: {
        relatedServices: ind.svcs.map((x: Item) => serviceIds[x.href.split('/').pop()!]).filter(Boolean),
      },
      status: 'published',
    } as any);
  }

  // -------------------------------------------------------------------------------------------
  // Projects & team
  // -------------------------------------------------------------------------------------------
  for (const [i, p] of content.projects.entries()) {
    const slug = p.t
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    const existing = await doc('api::project.project').findFirst({ filters: { title: { $eq: p.t } } as any });
    const data = {
      title: p.t,
      sector: p.sector,
      description: p.d,
      media: await mediaFrame(p.img, `project-${slug}`, p.imgLabel, p.imgLabel),
      metrics: [stat(p.m1, p.m1d), stat(p.m2, p.m2d)],
      featured: i < 3, // the design's Home "Recent Work" strip shows projects.slice(0, 3)
      order: i,
    };
    existing
      ? await doc('api::project.project').update({ documentId: existing.documentId, data, status: 'published' } as any)
      : await doc('api::project.project').create({ data, status: 'published' } as any);
  }

  for (const [i, m] of content.team.entries()) {
    const existing = await doc('api::team-member.team-member').findFirst({ filters: { role: { $eq: m.role } } as any });
    const data = { name: m.name, role: m.role, bio: m.bio, order: i };
    existing
      ? await doc('api::team-member.team-member').update({ documentId: existing.documentId, data, status: 'published' } as any)
      : await doc('api::team-member.team-member').create({ data, status: 'published' } as any);
  }

  // -------------------------------------------------------------------------------------------
  // Single types
  // -------------------------------------------------------------------------------------------
  await single(
    'api::global.global',
    {
      siteName: 'Forbes Water',
      defaultSeo: SEO.home,
      contact: {
        phone: '1300 000 000',
        phoneNote: '(placeholder)',
        email: 'enquiries@forbeswater.com.au',
        emailNote: '(placeholder)',
        coverage: 'Servicing all Australian states & territories',
        abn: 'ABN 00 000 000 000',
        abnNote: '(placeholder)',
      },
      footerTagline:
        'Independent water consulting, treatment, monitoring and management for Australian industry, communities and the environment.',
      copyright: '© 2026 Forbes Water Pty Ltd. All rights reserved.',
      legalLine: 'ABN 00 000 000 000 (placeholder) · Servicing Australia-wide',
      ctaBand: {
        heading: "Let's solve your water challenges",
        body: 'Independent advice, measurable outcomes, and a single accountable team from first sample to sustained performance.',
        button: { label: 'Request a Consultation', href: '/contact', variant: 'primary' },
      },
    },
    false
  );

  await single(
    'api::navigation.navigation',
    {
      mainItems: [
        { label: 'Home', href: '/', megaMenu: 'none' },
        { label: 'About', href: '/about', megaMenu: 'none' },
        { label: 'Services', href: '/services', megaMenu: 'services' },
        { label: 'Industries', href: '/industries', megaMenu: 'industries' },
        { label: 'Sustainability', href: '/sustainability', megaMenu: 'none' },
        { label: 'Projects', href: '/projects', megaMenu: 'none' },
      ],
      ctaButton: { label: 'Request Consultation', href: '/contact', variant: 'primary' },
      footerColumns: [
        { title: 'Services', source: 'services', links: [] },
        { title: 'Industries', source: 'industries', links: [] },
        {
          title: 'Company',
          source: 'manual',
          links: [
            { label: 'About Us', href: '/about', variant: 'ghost' },
            { label: 'Sustainability', href: '/sustainability', variant: 'ghost' },
            { label: 'Projects', href: '/projects', variant: 'ghost' },
            { label: 'Contact', href: '/contact', variant: 'ghost' },
          ],
        },
      ],
    },
    false
  );

  await single('api::home-page.home-page', {
    seo: SEO.home,
    heroEyebrow: 'Independent Water Specialists · Australia',
    heroHeading: 'Innovative water solutions for industry, communities & the environment',
    heroBody:
      'Forbes Water delivers specialist consulting, treatment, monitoring and management that optimise water quality, cut operating costs and keep you ahead of every compliance obligation.',
    heroPrimaryCta: { label: 'Request a Consultation', href: '/contact', variant: 'primary' },
    heroSecondaryCta: { label: 'View Our Services', href: '/services', variant: 'secondary' },
    heroStats: [
      stat('18+', 'Years of experience'),
      stat('340+', 'Sites optimised'),
      stat('100%', 'Independent advice'),
    ],
    heroMedia: await mediaFrame(SECTION_IMG.homeHero, 'home-hero', 'FORBES WATER · FIELD OPERATIONS', ''),
    expertiseHeading: {
      eyebrow: 'Our Expertise',
      heading: 'Every stage of the water cycle, one accountable team',
      linkLabel: 'All services →',
      linkHref: '/services',
    },
    whyHeading: {
      eyebrow: 'Why Forbes Water',
      heading: 'Advice that answers to your outcomes — not to equipment sales',
    },
    whyMedia: await mediaFrame(SECTION_IMG.homeWhy, 'home-why', 'ON-SITE WATER QUALITY AUDIT', ''),
    whyItems: num(content.why),
    industriesHeading: {
      eyebrow: 'Industries We Serve',
      heading: 'Solutions tuned to your sector',
      linkLabel: 'Explore industries →',
      linkHref: '/industries',
    },
    processHeading: { eyebrow: 'How We Work', heading: 'From first sample to sustained performance' },
    processItems: num(content.process),
    testimonial: {
      quote:
        'Forbes Water rebuilt our treatment strategy from the ground up. Water costs fell by a third, and our compliance reporting went from a monthly scramble to a non-event.',
      attribution: 'Operations Manager · Regional mining operation',
      note: '(representative client feedback)',
    },
    testimonialStats: [
      stat('32%', 'Average reduction in client water operating costs'),
      stat('1.2GL', 'Water recycled annually across client sites'),
      stat('Zero', 'Compliance breaches across managed programs'),
      stat('24h', 'Response time for urgent water quality events'),
    ],
    projectsHeading: {
      eyebrow: 'Recent Work',
      heading: 'Results our clients can measure',
      linkLabel: 'All projects →',
      linkHref: '/projects',
    },
  });

  await single('api::about-page.about-page', {
    seo: SEO.about,
    hero: {
      eyebrow: 'About Forbes Water',
      heading: 'Independent water specialists, accountable only to your outcomes',
      intro:
        'For more than 18 years, Forbes Water has helped Australian industry, agriculture and government get more from every drop — combining scientific rigour, field-proven engineering and genuinely independent advice.',
    },
    storyHeading: 'Built in the field, not the boardroom',
    storyBody: [
      "Forbes Water began with a simple observation: too many organisations were sold water treatment they didn't need, while the problems that actually cost them money went undiagnosed. We set out to be different — specialists who start with the water itself, not a product catalogue.",
      "Today our team supports more than 340 sites nationwide, from remote mine dewatering operations to municipal drinking water schemes. Because we're independent, every recommendation is judged on one measure only: whether it delivers for you.",
      'Our people are chemists, process engineers and environmental scientists who spend as much time on site as they do at a desk — which is exactly how we like it.',
    ]
      .map((p) => `<p>${p}</p>`)
      .join('\n'),
    storyMedia: await mediaFrame(SECTION_IMG.aboutStory, 'about-story', 'THE FORBES WATER TEAM ON SITE', ''),
    valuesHeading: { eyebrow: 'What We Stand For', heading: 'Four principles behind every engagement' },
    valuesItems: icon(content.values),
    teamHeading: { eyebrow: 'Leadership', heading: 'The people accountable for your water' },
  });

  await single('api::services-page.services-page', {
    seo: SEO.services,
    hero: {
      eyebrow: 'Our Services',
      heading: 'Water consulting, treatment & management services',
      intro:
        'Eight specialist capabilities, one accountable partner. Engage us for a single audit or an end-to-end program — every service is delivered by the same senior team, on the same independent terms.',
    },
    engagementHeading: {
      eyebrow: 'Ways to Engage',
      heading: 'Flexible engagement, from one-off audits to full management',
    },
    engagementItems: num(content.engagement),
  });

  await single('api::industries-page.industries-page', {
    seo: SEO.industries,
    hero: {
      eyebrow: 'Industries We Serve',
      heading: 'Sector-specific water expertise',
      intro:
        "Water challenges look very different on a mine site, a farm, and a hotel rooftop. We bring deep experience in each sector's regulations, risks and operating realities — so solutions fit your world, not a template.",
    },
  });

  await single('api::sustainability-page.sustainability-page', {
    seo: SEO.sustainability,
    hero: {
      eyebrow: 'Sustainability',
      heading: 'Sustainable water management that pays for itself',
      intro:
        "Sustainability isn't a report we write at the end — it's the engineering principle we start with. Using less, recycling more and protecting receiving environments almost always lowers operating cost too. We design for both.",
    },
    pillarsHeading: { eyebrow: 'Our Approach', heading: 'Four pillars of water stewardship' },
    pillarsItems: num(content.pillars),
    impactHeading: 'Measured impact across client sites',
    impactItems: content.impact.map((i: Item) => stat(i.v, i.d)),
    impactNote:
      'Figures shown are representative examples for design review — final metrics to be confirmed with Forbes Water.',
    practiceHeading: 'Stewardship in practice',
    practiceItems: icon(content.practice),
  });

  await single('api::projects-page.projects-page', {
    seo: SEO.projects,
    hero: {
      eyebrow: 'Projects & Case Studies',
      heading: 'Proven outcomes across Australia',
      intro:
        'A selection of engagements showing how independent advice and disciplined delivery translate into lower costs, secure compliance and healthier water.',
      note: 'Case studies below are representative examples for design review — to be replaced with approved client projects.',
    },
  });

  await single('api::contact-page.contact-page', {
    seo: SEO.contact,
    hero: {
      eyebrow: 'Contact',
      heading: "Let's solve your water challenges",
      intro:
        "Tell us about your site and what you're trying to achieve. A senior specialist — not a sales rep — will come back to you within one business day.",
    },
    directContactHeading: 'Direct contact',
    nextStepsHeading: 'What happens next',
    nextStepsItems: [
      { number: '01', title: 'A specialist reviews your enquiry and site context', description: '' },
      { number: '02', title: 'We book a scoping call — usually within 48 hours', description: '' },
      { number: '03', title: 'You receive a clear, fixed-scope proposal', description: '' },
    ],
    formNote: '* Required fields.',
    successHeading: "Thanks — we've got it.",
    successBody:
      'A senior water specialist will review your enquiry and respond within one business day. Urgent water quality event? Call us directly.',
    successButtonLabel: 'Send another enquiry',
    industryOptions: [
      'Mining & Resources',
      'Agriculture',
      'Commercial & Industrial',
      'Government & Municipal',
      'Hospitality & Facilities',
      'Other',
    ],
  });

  const counts = {
    services: await doc('api::service.service').count({}),
    industries: await doc('api::industry.industry').count({}),
    projects: await doc('api::project.project').count({}),
    team: await doc('api::team-member.team-member').count({}),
  };
  console.log('\nseeded:', counts);
  if (mediaFailures) {
    console.log(`\n⚠  ${mediaFailures} image(s) could not be fetched — media fields left empty.`);
    console.log('   Re-run with network access, or upload real photography in the Media Library.');
  }

  await app.destroy();
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
